version: "3.9"

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./app
    ports:
      - "4200:80"
    restart: unless-stopped